apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-mysql-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-python-mysql-app
  template:
    metadata:
      labels:
        app: my-python-mysql-app
    spec:
      containers:
      - name: my-app
        image: magiwu/my-python-mysql-app:latest
        imagePullPolicy: Always
        command: [ "python" ]
        args:
          - -m
          - main
